### ISSUE TITLE
1.20.6中空指针异常

### ISSUE THREAD

**Issue by shixiaoxiao233** [CarmJos/MoeTeleport#15]
服务器版本:leaves-1.20.6
在玩家使用插件相关命令后会产生一段WARN报错，以下是相关日志：
```text
[06:51:53] [Server thread/INFO]: Quiet_afternoon issued server command: /back
[06:51:53] [Craft Scheduler Thread - 6872 - MoeTeleport/WARN]: [MoeTeleport] Plugin MoeTeleport v4.0.3 generated an exception while executing task 28
java.lang.NoClassDefFoundError: Could not initialize class cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager.tickQueue(TeleportManager.java:64) ~[MoeTeleport-4.0.3.jar:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager$1.run(TeleportManager.java:37) ~[MoeTeleport-4.0.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Craft Scheduler Thread - 62 - MoeTeleport"]
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect.<clinit>(ParticleEffect.java:1304) ~[MoeTeleport-4.0.3.jar:?]
	... 8 more
[06:51:54] [Craft Scheduler Thread - 6896 - MoeTeleport/WARN]: [MoeTeleport] Plugin MoeTeleport v4.0.3 generated an exception while executing task 28
java.lang.NoClassDefFoundError: Could not initialize class cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager.tickQueue(TeleportManager.java:64) ~[MoeTeleport-4.0.3.jar:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager$1.run(TeleportManager.java:37) ~[MoeTeleport-4.0.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Craft Scheduler Thread - 62 - MoeTeleport"]
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect.<clinit>(ParticleEffect.java:1304) ~[MoeTeleport-4.0.3.jar:?]
	... 8 more
[06:51:55] [Craft Scheduler Thread - 6882 - MoeTeleport/WARN]: [MoeTeleport] Plugin MoeTeleport v4.0.3 generated an exception while executing task 28
java.lang.NoClassDefFoundError: Could not initialize class cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager.tickQueue(TeleportManager.java:64) ~[MoeTeleport-4.0.3.jar:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager$1.run(TeleportManager.java:37) ~[MoeTeleport-4.0.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Craft Scheduler Thread - 62 - MoeTeleport"]
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect.<clinit>(ParticleEffect.java:1304) ~[MoeTeleport-4.0.3.jar:?]
	... 8 more
[06:51:56] [Craft Scheduler Thread - 6896 - MoeTeleport/WARN]: [MoeTeleport] Plugin MoeTeleport v4.0.3 generated an exception while executing task 28
java.lang.NoClassDefFoundError: Could not initialize class cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager.executeTeleport(TeleportManager.java:145) ~[MoeTeleport-4.0.3.jar:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager.tickQueue(TeleportManager.java:72) ~[MoeTeleport-4.0.3.jar:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager$1.run(TeleportManager.java:37) ~[MoeTeleport-4.0.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.20.6.jar:1.20.6-214-2a7fc43]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Craft Scheduler Thread - 62 - MoeTeleport"]
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.lib.praticle.ParticleEffect.<clinit>(ParticleEffect.java:1304) ~[MoeTeleport-4.0.3.jar:?]
	at MoeTeleport-4.0.3.jar/cc.carm.plugin.moeteleport.manager.TeleportManager.tickQueue(TeleportManager.java:64) ~[MoeTeleport-4.0.3.jar:?]
	... 7 more
```

**Comment by CarmJos** [comment]
您好，经检查，可能是leaves服务端对粒子效果部分做了变更，导致无法正常初始化效果。

**Comment by CarmJos** [comment]
您可以尝试关闭配置文件中的 **传送特效** ，问题应当会解决；

**Comment by shixiaoxiao233** [comment]
经测试，关闭特效后后台正常无报错
